# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ghcr actions

on:
  schedule:
    - cron: '21 21 * * *'

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete 'PR' containers older than a week
        uses: snok/container-retention-policy@v1.4.2
        with:
          image-names: sda-pipeline
          filter-tags: PR*, sha-*
          cut-off: A week ago UTC
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all containers older than treee months, using a wildcard
        uses: snok/container-retention-policy@v1.4.2
        with:
          image-names: sda-pipeline
          filter-tags: v*
          cut-off: Three months ago UTC
          account-type: org
          org-name: ${{ github.repository_owner }}
          keep-at-least: 2
          skip-tags: latest
          token: ${{ secrets.GITHUB_TOKEN }}
